#pragma once

#include <stddef.h>
#include <stdint.h>

// Generated by tools/generate_dome_layout_header.py.
// Edit templates/dome-layouts/mr-baddeley-complex-dome-mk4.json instead.

namespace DomeLayout {

static constexpr int kSchemaRevision = 1;
static constexpr int kTemplateRevision = 1;
static constexpr const char *kTemplateId = "mr-baddeley-complex-dome-mk4";
static constexpr const char *kTemplateName = "Mr Baddeley Complex Dome MK4";
static constexpr const char *kModel = "MK4";
static constexpr const char *kSource = "AstroPixelsPlus data/panels.html";
static constexpr const char *kCoordinateSpaceViewBox = "0 0 480 480";
static constexpr float kDefaultPointMarkerRadius = 6.0f;

enum class DomeLayoutGeometryType {
    SvgPath,
    Circle,
    Ellipse,
    Point,
};

struct DomeLayoutPoint {
    bool present;
    float x;
    float y;
};

struct DomeLayoutCallout {
    bool present;
    float x;
    float y;
    float r;
    bool connectorPresent;
    float connectorX;
    float connectorY;
};

struct DomeLayoutElement {
    const char *id;
    const char *label;
    const char *elementType;
    const char *panelKind;
    const char *mountedOn;
    bool inLayout;
    bool commandable;
    const char *const *aliases;
    size_t aliasCount;
    const char *const *capabilities;
    size_t capabilityCount;
    int renderOrder;
    DomeLayoutGeometryType geometryType;
    const char *svgPath;
    float cx;
    float cy;
    float r;
    float rx;
    float ry;
    float rotation;
    DomeLayoutPoint labelAnchor;
    DomeLayoutCallout callout;
};

static constexpr const char *const kAliases_HP2[] = {
    "RHP",
};

static constexpr const char *const kCapabilities_HP2[] = {
    "light",
    "aim",
    "effect",
};

static constexpr const char *const kAliases_RPSI[] = {
    "Rear PSI",
};

static constexpr const char *const kCapabilities_RPSI[] = {
    "light",
    "effect",
};

static constexpr const char *const kCapabilities_P7[] = {
    "open",
    "close",
    "flutter",
};

static constexpr const char *const kAliases_MP[] = {
    "Magic Panel",
};

static constexpr const char *const kCapabilities_P4[] = {
    "open",
    "close",
    "flutter",
};

static constexpr const char *const kCapabilities_P3[] = {
    "open",
    "close",
    "flutter",
};

static constexpr const char *const kCapabilities_P2[] = {
    "open",
    "close",
    "flutter",
};

static constexpr const char *const kCapabilities_P1[] = {
    "open",
    "close",
    "flutter",
};

static constexpr const char *const kAliases_HP1[] = {
    "FHP",
};

static constexpr const char *const kCapabilities_HP1[] = {
    "light",
    "aim",
    "effect",
};

static constexpr const char *const kAliases_FPSI[] = {
    "Front PSI",
};

static constexpr const char *const kCapabilities_FPSI[] = {
    "light",
    "effect",
};

static constexpr const char *const kCapabilities_P13[] = {
    "open",
    "close",
    "flutter",
};

static constexpr const char *const kAliases_FLD[] = {
    "FLDs",
    "top_fld",
    "bottom_fld",
};

static constexpr const char *const kCapabilities_FLD[] = {
    "light",
    "effect",
};

static constexpr const char *const kCapabilities_P11[] = {
    "open",
    "close",
    "flutter",
};

static constexpr const char *const kCapabilities_RLD[] = {
    "light",
    "effect",
};

static constexpr const char *const kCapabilities_PP4[] = {
    "open",
    "close",
    "flutter",
};

static constexpr const char *const kCapabilities_PP3[] = {
    "open",
    "close",
    "flutter",
};

static constexpr const char *const kAliases_HP3[] = {
    "THP",
};

static constexpr const char *const kCapabilities_HP3[] = {
    "light",
    "aim",
    "effect",
};

static constexpr const char *const kCapabilities_PP2[] = {
    "open",
    "close",
    "flutter",
};

static constexpr const char *const kCapabilities_PP1[] = {
    "open",
    "close",
    "flutter",
};

static constexpr const char *const kCapabilities_PP6[] = {
    "open",
    "close",
    "flutter",
};

static constexpr const char *const kCapabilities_PP5[] = {
    "open",
    "close",
    "flutter",
};

static constexpr DomeLayoutElement kElements[] = {
    {
        "HP2",
        "HP2",
        "holo",
        nullptr,
        nullptr,
        true,
        false,
        kAliases_HP2,
        1,
        kCapabilities_HP2,
        3,
        10,
        DomeLayoutGeometryType::Ellipse,
        nullptr,
        240.0f,
        81.0f,
        0.0f,
        14.1f,
        10.9f,
        0.0f,
        { true, 240.0f, 81.0f },
        { false, 0.0f, 0.0f, 0.0f, false, 0.0f, 0.0f },
    },

    {
        "P8",
        "P8",
        "panel",
        "fixed",
        nullptr,
        true,
        false,
        nullptr,
        0,
        nullptr,
        0,
        20,
        DomeLayoutGeometryType::SvgPath,
        "M 272.8,71.2 A 172,172 0 0 1 318.1,86.7 L 306.3,109.9 A 146,146 0 0 0 267.9,96.7 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 309.3f, 34.6f },
        { true, 309.3f, 38.6f, 14.0f, true, 301.2f, 62.2f },
    },

    {
        "RPSI",
        "RPSI",
        "psi",
        nullptr,
        "P8",
        true,
        false,
        kAliases_RPSI,
        1,
        kCapabilities_RPSI,
        2,
        21,
        DomeLayoutGeometryType::Point,
        nullptr,
        301.2f,
        62.2f,
        6.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 309.3f, 43.6f },
        { true, 309.3f, 38.6f, 14.0f, true, 301.2f, 62.2f },
    },

    {
        "P7",
        "P7",
        "panel",
        "ring",
        nullptr,
        true,
        true,
        nullptr,
        0,
        kCapabilities_P7,
        3,
        30,
        DomeLayoutGeometryType::SvgPath,
        "M 331.1,94.1 A 172,172 0 0 1 391.9,159.3 L 368.9,171.5 A 146,146 0 0 0 317.4,116.2 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 395.8f, 94.7f },
        { true, 395.8f, 94.7f, 12.0f, true, 377.5f, 111.8f },
    },

    {
        "P6",
        "P6",
        "panel",
        "fixed",
        nullptr,
        true,
        false,
        nullptr,
        0,
        nullptr,
        0,
        40,
        DomeLayoutGeometryType::SvgPath,
        "M 398.3,172.8 A 172,172 0 0 1 409.4,210.1 L 383.8,214.6 A 146,146 0 0 0 374.4,183.0 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 444.2f, 172.5f },
        { true, 444.2f, 179.5f, 16.0f, true, 420.3f, 186.6f },
    },

    {
        "MP",
        "MP",
        "panel",
        "fixed",
        nullptr,
        true,
        false,
        kAliases_MP,
        1,
        nullptr,
        0,
        41,
        DomeLayoutGeometryType::SvgPath,
        "M 398.3,172.8 A 172,172 0 0 1 409.4,210.1 L 383.8,214.6 A 146,146 0 0 0 374.4,183.0 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 444.2f, 179.5f },
        { true, 444.2f, 179.5f, 16.0f, true, 420.3f, 186.6f },
    },

    {
        "P5",
        "P5",
        "panel",
        "fixed",
        nullptr,
        true,
        false,
        nullptr,
        0,
        nullptr,
        0,
        42,
        DomeLayoutGeometryType::SvgPath,
        "M 398.3,172.8 A 172,172 0 0 1 409.4,210.1 L 383.8,214.6 A 146,146 0 0 0 374.4,183.0 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 444.2f, 186.5f },
        { true, 444.2f, 179.5f, 16.0f, true, 420.3f, 186.6f },
    },

    {
        "P4",
        "P4",
        "panel",
        "ring",
        nullptr,
        true,
        true,
        nullptr,
        0,
        kCapabilities_P4,
        3,
        50,
        DomeLayoutGeometryType::SvgPath,
        "M 411.3,225.0 A 172,172 0 0 1 395.9,312.7 L 372.3,301.7 A 146,146 0 0 0 385.4,227.3 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 449.8f, 277.0f },
        { true, 449.8f, 277.0f, 12.0f, true, 425.1f, 272.6f },
    },

    {
        "P3",
        "P3",
        "panel",
        "ring",
        nullptr,
        true,
        true,
        nullptr,
        0,
        kCapabilities_P3,
        3,
        60,
        DomeLayoutGeometryType::SvgPath,
        "M 389.0,326.0 A 172,172 0 0 1 365.8,357.3 L 346.8,339.6 A 146,146 0 0 0 366.4,313.0 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 411.2f, 366.7f },
        { true, 411.2f, 366.7f, 12.0f, true, 391.1f, 351.8f },
    },

    {
        "P2",
        "P2",
        "panel",
        "ring",
        nullptr,
        true,
        true,
        nullptr,
        0,
        kCapabilities_P2,
        3,
        70,
        DomeLayoutGeometryType::SvgPath,
        "M 355.1,367.8 A 172,172 0 0 1 323.4,390.4 L 310.8,367.7 A 146,146 0 0 0 337.7,348.5 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 363.7f, 413.4f },
        { true, 363.7f, 413.4f, 12.0f, true, 349.2f, 393.1f },
    },

    {
        "P1",
        "P1",
        "panel",
        "ring",
        nullptr,
        true,
        true,
        nullptr,
        0,
        kCapabilities_P1,
        3,
        80,
        DomeLayoutGeometryType::SvgPath,
        "M 310.0,397.1 A 172,172 0 0 1 272.8,408.8 L 267.9,383.3 A 146,146 0 0 0 299.4,373.4 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 304.1f, 443.1f },
        { true, 304.1f, 443.1f, 12.0f, true, 296.5f, 419.3f },
    },

    {
        "HP1",
        "HP1",
        "holo",
        nullptr,
        nullptr,
        true,
        false,
        kAliases_HP1,
        1,
        kCapabilities_HP1,
        3,
        90,
        DomeLayoutGeometryType::Ellipse,
        nullptr,
        237.2f,
        399.0f,
        0.0f,
        16.5f,
        10.9f,
        181.0f,
        { true, 237.2f, 399.0f },
        { false, 0.0f, 0.0f, 0.0f, false, 0.0f, 0.0f },
    },

    {
        "P14",
        "P14",
        "panel",
        "fixed",
        nullptr,
        true,
        false,
        nullptr,
        0,
        nullptr,
        0,
        100,
        DomeLayoutGeometryType::SvgPath,
        "M 198.4,406.9 A 172,172 0 0 1 154.0,389.0 L 167.0,366.4 A 146,146 0 0 0 204.7,381.7 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 160.2f, 433.5f },
        { true, 160.2f, 437.5f, 14.0f, true, 169.6f, 414.3f },
    },

    {
        "FPSI",
        "FPSI",
        "psi",
        nullptr,
        "P14",
        true,
        false,
        kAliases_FPSI,
        1,
        kCapabilities_FPSI,
        2,
        101,
        DomeLayoutGeometryType::Point,
        nullptr,
        169.6f,
        414.3f,
        6.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 160.2f, 442.5f },
        { true, 160.2f, 437.5f, 14.0f, true, 169.6f, 414.3f },
    },

    {
        "P13",
        "P13",
        "panel",
        "ring",
        nullptr,
        true,
        true,
        nullptr,
        0,
        kCapabilities_P13,
        3,
        110,
        DomeLayoutGeometryType::SvgPath,
        "M 138.9,379.2 A 172,172 0 0 1 124.9,367.8 L 142.3,348.5 A 146,146 0 0 0 154.2,358.1 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 106.0f, 405.5f },
        { true, 106.0f, 405.5f, 12.0f, true, 121.7f, 386.1f },
    },

    {
        "P12",
        "P12",
        "panel",
        "fixed",
        nullptr,
        true,
        false,
        nullptr,
        0,
        nullptr,
        0,
        120,
        DomeLayoutGeometryType::SvgPath,
        "M 112.2,355.1 A 172,172 0 0 1 88.1,320.7 L 111.1,308.5 A 146,146 0 0 0 131.5,337.7 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 65.5f, 358.2f },
        { true, 65.5f, 362.2f, 14.0f, true, 86.0f, 347.8f },
    },

    {
        "FLD",
        "FLD",
        "logic",
        nullptr,
        "P12",
        true,
        false,
        kAliases_FLD,
        3,
        kCapabilities_FLD,
        2,
        121,
        DomeLayoutGeometryType::Point,
        nullptr,
        86.0f,
        347.8f,
        6.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 65.5f, 367.2f },
        { true, 65.5f, 362.2f, 14.0f, true, 86.0f, 347.8f },
    },

    {
        "P11",
        "P11",
        "panel",
        "ring",
        nullptr,
        true,
        true,
        nullptr,
        0,
        kCapabilities_P11,
        3,
        130,
        DomeLayoutGeometryType::SvgPath,
        "M 80.5,304.4 A 172,172 0 0 1 74.7,287.4 L 99.7,280.2 A 146,146 0 0 0 104.6,294.7 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 38.6f, 309.3f },
        { true, 38.6f, 309.3f, 12.0f, true, 62.2f, 301.2f },
    },

    {
        "P10",
        "P10",
        "panel",
        "fixed",
        nullptr,
        true,
        false,
        nullptr,
        0,
        nullptr,
        0,
        140,
        DomeLayoutGeometryType::SvgPath,
        "M 70.6,269.9 A 172,172 0 0 1 88.1,159.3 L 111.1,171.5 A 146,146 0 0 0 96.2,265.4 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 29.6f, 206.7f },
        { true, 29.6f, 206.7f, 11.0f, true, 54.3f, 210.6f },
    },

    {
        "P9",
        "P9",
        "panel",
        "fixed",
        nullptr,
        true,
        false,
        nullptr,
        0,
        nullptr,
        0,
        150,
        DomeLayoutGeometryType::SvgPath,
        "M 97.4,143.8 A 172,172 0 0 1 192.6,74.7 L 199.8,99.7 A 146,146 0 0 0 119.0,158.4 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 114.8f, 63.7f },
        { true, 114.8f, 67.7f, 14.0f, true, 129.5f, 87.9f },
    },

    {
        "RLD",
        "RLD",
        "logic",
        nullptr,
        "P9",
        true,
        false,
        nullptr,
        0,
        kCapabilities_RLD,
        2,
        151,
        DomeLayoutGeometryType::Point,
        nullptr,
        129.5f,
        87.9f,
        6.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 114.8f, 72.7f },
        { true, 114.8f, 67.7f, 14.0f, true, 129.5f, 87.9f },
    },

    {
        "PP4",
        "PP4",
        "panel",
        "pie",
        nullptr,
        true,
        true,
        nullptr,
        0,
        kCapabilities_PP4,
        3,
        200,
        DomeLayoutGeometryType::SvgPath,
        "M 184.6,135.8 A 118,118 0 0 1 293.6,134.9 L 264.5,191.9 A 54,54 0 0 0 214.6,192.3 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 240.0f, 154.0f },
        { false, 0.0f, 0.0f, 0.0f, false, 0.0f, 0.0f },
    },

    {
        "PP3",
        "PP3",
        "panel",
        "pie",
        nullptr,
        true,
        true,
        nullptr,
        0,
        kCapabilities_PP3,
        3,
        210,
        DomeLayoutGeometryType::SvgPath,
        "M 302.5,139.9 A 118,118 0 0 1 357.8,233.8 L 293.9,237.2 A 54,54 0 0 0 268.6,194.2 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 296.0f, 216.0f },
        { false, 0.0f, 0.0f, 0.0f, false, 0.0f, 0.0f },
    },

    {
        "HP3",
        "HP3",
        "holo",
        nullptr,
        "PP3",
        true,
        false,
        kAliases_HP3,
        1,
        kCapabilities_HP3,
        3,
        211,
        DomeLayoutGeometryType::Circle,
        nullptr,
        320.4f,
        172.5f,
        6.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 320.4f, 172.5f },
        { false, 0.0f, 0.0f, 0.0f, false, 0.0f, 0.0f },
    },

    {
        "PP2",
        "PP2",
        "panel",
        "pie",
        nullptr,
        true,
        true,
        nullptr,
        0,
        kCapabilities_PP2,
        3,
        220,
        DomeLayoutGeometryType::SvgPath,
        "M 357.9,244.1 A 118,118 0 0 1 304.3,339.0 L 269.4,285.3 A 54,54 0 0 0 294.0,241.9 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 314.9f, 282.3f },
        { false, 0.0f, 0.0f, 0.0f, false, 0.0f, 0.0f },
    },

    {
        "PP1",
        "PP1",
        "panel",
        "pie",
        nullptr,
        true,
        true,
        nullptr,
        0,
        kCapabilities_PP1,
        3,
        230,
        DomeLayoutGeometryType::SvgPath,
        "M 295.4,344.2 A 118,118 0 0 1 186.4,345.1 L 215.5,288.1 A 54,54 0 0 0 265.4,287.7 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 240.8f, 326.0f },
        { false, 0.0f, 0.0f, 0.0f, false, 0.0f, 0.0f },
    },

    {
        "PP6",
        "PP6",
        "panel",
        "pie",
        nullptr,
        true,
        true,
        nullptr,
        0,
        kCapabilities_PP6,
        3,
        240,
        DomeLayoutGeometryType::SvgPath,
        "M 177.5,340.1 A 118,118 0 0 1 122.2,246.2 L 186.1,242.8 A 54,54 0 0 0 211.4,285.8 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 165.9f, 283.6f },
        { false, 0.0f, 0.0f, 0.0f, false, 0.0f, 0.0f },
    },

    {
        "PP5",
        "PP5",
        "panel",
        "pie",
        nullptr,
        true,
        true,
        nullptr,
        0,
        kCapabilities_PP5,
        3,
        250,
        DomeLayoutGeometryType::SvgPath,
        "M 122.1,235.9 A 118,118 0 0 1 175.7,141.0 L 210.6,194.7 A 54,54 0 0 0 186.0,238.1 Z",
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        { true, 165.1f, 197.7f },
        { false, 0.0f, 0.0f, 0.0f, false, 0.0f, 0.0f },
    },

};

static constexpr size_t kElementCount = sizeof(kElements) / sizeof(kElements[0]);

}  // namespace DomeLayout
